[package]
name = "nox_test"
version = "0.1.0"
edition = "2021"

[dependencies]
iced_aw = "0.11.0"
iced = {version = "0.13.1", features = ["debug"]}
sqlite = "0.36.1"
rsa = "0.9.6"
rand = "0.8"
rfd = "0.15.0"
sha2 = "0.10.8"
aes-gcm = "0.10.3"
pem = "1.0"
hex = "0.4"